name: Lint
on: [push, pull_request]
jobs:
  php-cs-differ:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: PHP CS Differ
        uses: mrsuh/actions-php-cs-differ@master
        with:
          directory: 'src/'  
          